### ISSUE TITLE
能否拉大界面？默认界面高度不到屏幕的一半

### ISSUE THREAD

**Issue by fodereas** [ric2cn/webdiary#1]
试了好几个历史管理类插件，都不太合胃口
安装你这个插件  一点开，好家伙，这正是我要的插件！
但是感觉默认界面有点小，又是固定的，没法在边框处拉大
不知道能否改进？
或者可以作为一个网页打开，占满整个浏览器区域屏幕，而不是这种小弹窗？
按站点删除历史记录太好用！

**Comment by lalinking** [comment]
可以作为一个网页打开的，插件的首页地址是：
chrome-extension://jokoalpdfppeolhnfljmfecbifcfadhh/page/main/page.html

我试过设置成首页可以打开。
做成这种按钮纯粹是方便按快捷键打开。

可能是你显示器分辨率大看起来不太协调吧，可以考虑这种情况。不过 ”拉大“ 这种交互我估计是没法支持的，可能在设置页面加一个设置，手动填一个数字或百分比？ 目前页面大小是 50rem * 36 rem (1rem=17像素)
